[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#c9a666"
backgroundColor = "#141821"
secondaryBackgroundColor = "#1b2029"
textColor = "#eae7e1"

[browser]
gatherUsageStats = false

[server]
headless = true